## Red Hat Intel Openshift Lab config tool
#################################################################################
## vim: noai:ts=2:sw=2

---
- name: "Auth Provider - HTPassswd"
  include_tasks: ./playbooks/auth_provider_htpasswd.yaml
  when:
    - "cluster.auth.provider.htpasswd is defined"
